### ISSUE TITLE
Button login-page no longer visible

### ISSUE THREAD

**Issue by kMikaZu** [wpsocio/wptelegram-login#53]
I have a website where the button no longer seems to be visible. What do you need from logs etc to investigate this?

**Comment by irshadahmad21** [comment]
A few questions:
1. Does it work on the default WordPress login page?
2. How did you add the login button to the page, using shortcode?
3. Did you try in an incognito window?
4. Have you already connected your Telegram account and are logged in to your website?
5. What is "Show if user is" option set to?

**Comment by kMikaZu** [comment]
1. Nope
2. I'm using the default login page only. 
3. Yes, in different browsers and also mobile network (to be sure not to have any protection active). 
4. Yes
5. "Each" and tried others.

**Comment by irshadahmad21** [comment]
Thanks

Can you please share a full page screenshot of the login page along with the URL in the browser?

If not here, you can share with our support on Telegram - <a href="https://t.me/WPTelegramSupport">@WPTelegramSupport</a>

**Comment by irshadahmad21** [comment]
> URL: https://www.dayofdays.be/wp-login.php
> 
> Screenshot: https://screenshots.dyna-mika.be/2ZvDRsYh

Thank you. Do you have any caching or SEO plugin active that strips out third-party `<script>` tags?

**Comment by irshadahmad21** [comment]
Having a brief look at the page source, I see that there is some `siteground-optimizer` messing with Telegram script.

**Comment by irshadahmad21** [comment]
It seems like you have [SG Speed Optimizer](https://wordpress.org/plugins/sg-cachepress/) active.

You can turn off **_Combine JavaScript Files_** option in `Speed Optimizer > Frontend > JavaScript` section

**Comment by kMikaZu** [comment]
Found it the same time :-)
I can also add exclusions, but the Telegram plugin doesn't seem to be listed. Does it make use of other default JavaScript?

**Comment by irshadahmad21** [comment]
> I can also add exclusions, but the Telegram plugin doesn't seem to be listed. Does it make use of other default JavaScript?

Yeah, I can't see it either. May be reach out to that plugin support to see how you can add such a third-party script to the exclusion list.

**Comment by irshadahmad21** [comment]
You can give this snippet a shot

```php
add_filter( 'sgo_javascript_combine_excluded_external_paths', function ( $paths ) {
    $paths[] = 'telegram.org';
    return $paths;
} );
```
